GRANT USAGE ON SCHEMA rincones_llaneros TO postgres;
GRANT SELECT, INSERT, UPDATE, DELETE ON ALL TABLES IN SCHEMA rincones_llaneros TO postgres;
ALTER DEFAULT PRIVILEGES IN SCHEMA rincones_llaneros GRANT SELECT, INSERT, UPDATE, DELETE ON TABLES TO postgres;